fix(packaging): 把 templates/ 和 static/ 加入 setuptools package-data
$ pip install . 打的 wheel 之前丢失这两个目录，导致容器内
RuntimeError: Directory .../digitalplat_auto_register/static does not exist